// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3_oekZHWxpDXhZdUlYqKFNCadfn29MU',
    appId: '1:980138640170:web:df15d5d5d5246648905453',
    messagingSenderId: '980138640170',
    projectId: 'carbon-footprint-tracker-298a3',
    authDomain: 'carbon-footprint-tracker-298a3.firebaseapp.com',
    storageBucket: 'carbon-footprint-tracker-298a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvh2SDeYBzjxBTBSI2EhdbaKXUn8MRCY',
    appId: '1:980138640170:android:7f1eea431602a52a905453',
    messagingSenderId: '980138640170',
    projectId: 'carbon-footprint-tracker-298a3',
    storageBucket: 'carbon-footprint-tracker-298a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9HpOv3F7nYZQfXMiAK_uMaKsw3GXb88c',
    appId: '1:980138640170:ios:b5c540fdcf1b51f6905453',
    messagingSenderId: '980138640170',
    projectId: 'carbon-footprint-tracker-298a3',
    storageBucket: 'carbon-footprint-tracker-298a3.firebasestorage.app',
    iosBundleId: 'com.example.carbonFootprintTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9HpOv3F7nYZQfXMiAK_uMaKsw3GXb88c',
    appId: '1:980138640170:ios:b5c540fdcf1b51f6905453',
    messagingSenderId: '980138640170',
    projectId: 'carbon-footprint-tracker-298a3',
    storageBucket: 'carbon-footprint-tracker-298a3.firebasestorage.app',
    iosBundleId: 'com.example.carbonFootprintTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU3_oekZHWxpDXhZdUlYqKFNCadfn29MU',
    appId: '1:980138640170:web:3b08cd9a1c6e1518905453',
    messagingSenderId: '980138640170',
    projectId: 'carbon-footprint-tracker-298a3',
    authDomain: 'carbon-footprint-tracker-298a3.firebaseapp.com',
    storageBucket: 'carbon-footprint-tracker-298a3.firebasestorage.app',
  );
}
